server:
  port: 8081

spring:
  application:
    name: oauthclient

  security:
    jwt:
      secret: my_super_secure_and_long_jwt_secret_key_123!  # ✅ At least 32 characters

    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID         # ⛔ Replace with your actual Google client ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET # ⛔ Replace with your actual Google client secret
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
