server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      paymentApi:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5

logging:
  level:
    io.github.resilience4j: DEBUG
